trainset:
  name: driving
  root_dir: datasets/driving
  n_workers: 8
  drop_last: true

  n_points: 8192
  max_depth: 50.0

  focal_type:
    - 15mm_focallength
    - 35mm_focallength

  moving_dir:
    - scene_forwards
    - scene_backwards

  speed:
    - slow
    - fast

  flow_dir:
    - into_future
    - into_past

  augmentation:
    enabled: true
    color_jitter:
      enabled: true
      brightness: 0.3
      contrast: 0.3
      saturation: 0.3
      hue: 0.159  # 0.5/3.14
    random_horizontal_flip:
      enabled: true
    random_vertical_flip:
      enabled: false
    random_crop:
      enabled: true
      crop_size: [768, 384]
    random_scale:
      enabled: false

valset:
  name: kitti
  root_dir: datasets/kitti_scene_flow
  split: training200
  n_workers: 8

  disp_provider: kitti
  max_depth: 90
  n_points: 8192

  augmentation:
    enabled: false

model:
  batch_size: 8
  freeze_bn: true

  ids:
    enabled: true
    sensor_size_divisor: 32

  pwc2d:
    norm:
      feature_pyramid: batch_norm
      flow_estimator: null
      context_network: null
    max_displacement: 4

  pwc3d:
    norm:
      feature_pyramid: batch_norm
      correlation: null
      flow_estimator: null
    k: 16

  loss2d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

  loss3d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

training:
  max_epochs: 800
  optimizer: adam
  lr:
    init_value: 0.0001
    momentum: 0.9
    decay_rate: 0.5
    decay_milestones: 800
  weight_decay: 0.000001
  bias_decay: 0.0

log:
  dir: outputs/driving
  run_name: driving
  save_ckpt: true
  save_ckpt_every_n_epochs: 1
  save_summary_every_n_steps: 100

ckpt:
  path: null
  resume: false

port: random  # for multi-gpu training
amp: false
