trainset:
  name: kitti
  root_dir: datasets/kitti_scene_flow
  split: training160
  n_workers: 8
  drop_last: false

  disp_provider: kitti
  max_depth: 90
  n_points: 8192

  augmentation:
    enabled: true
    color_jitter:
      enabled: true
      brightness: 0.4
      contrast: 0.4
      saturation: 0.2
      hue: 0.127  # 0.4/3.14
    random_horizontal_flip:
      enabled: true
    random_vertical_flip:
      enabled: false
    random_crop:
      enabled: false
    random_scale:
      enabled: true
      scale_range: [1.0, 1.5]

valset:
  name: kitti
  root_dir: datasets/kitti_scene_flow
  split: training40
  n_workers: 8

  disp_provider: kitti
  max_depth: 90
  n_points: 8192

  augmentation:
    enabled: false

model:
  batch_size: 8
  freeze_bn: true

  ids:
    enabled: true
    sensor_size_divisor: 32

  pwc2d:
    norm:
      feature_pyramid: batch_norm
      flow_estimator: null
      context_network: null
    max_displacement: 4

  pwc3d:
    norm:
      feature_pyramid: batch_norm
      correlation: null
      flow_estimator: null
    k: 16

  loss2d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

  loss3d:
    level_weights: [8, 4, 2, 1, 0.5]
    order: l1

training:
  max_epochs: 300
  optimizer: adam
  lr:
    init_value: 0.00005
    momentum: 0.9
    decay_rate: 0.5
    decay_milestones: 300
  weight_decay: 0.000001
  bias_decay: 0.0

log:
  dir: outputs/kitti
  run_name: kitti
  save_ckpt: true
  save_ckpt_every_n_epochs: 1
  save_summary_every_n_steps: 100

ckpt:
  path: null
  resume: false

port: random  # for multi-gpu training
amp: false
