# @package _global_
training:
  opt: adamw
  momentum: 0.9
  weight_decay: 1e-6
  grad_max_norm: 20
  accum_iter: 1

  sched: cosine
  epochs: 300
  lr: 1e-3
  min_lr: 1e-5
  warmup_lr: 1e-5
  warmup_epochs: 2
  cooldown_epochs: 0
  decay_rate: 0.1  # only for step
  decay_epochs: 1  # only for step

override:
  trainset:
    with_image: false
  valset:
    with_image: false
